[tool.ruff]
line-length = 90
exclude = ['cases_update']
lint.extend-select = ['Q', 'RUF100', 'C90', 'UP', 'I']
lint.mccabe = { max-complexity = 10 }
lint.isort = { known-first-party = ['pytest_examples'] }
target-version = 'py39'