- name: Load config on to device using aruba_config
  community.network.aruba_config:
    commands: "{{ command_list }}"
    replace: block
    match: none
    save_when: never
  register: cfg_output_aos
  until: cfg_output_aos.failed == false
  retries: "{{ RETRIES }}"
  when: command_list | reject('regex', '^[\\s!]*$') | length > 0

- name: Debug when command_list is empty
  ansible.builtin.debug:
    msg: "Command_list is empty. Not pushing config."
  when: command_list | reject('regex', '^[\\s!]*$') | length == 0
