# IADFOS01# ping 10.99.80.52 repetitions 1
# PING 10.99.80.52 (10.99.80.52) 100(128) bytes of data.
# 108 bytes from 10.99.80.52: icmp_seq=1 ttl=64 time=0.179 ms
#
# --- 10.99.80.52 ping statistics ---
# 1 packets transmitted, 1 received, 0% packet loss, time 0ms
# rtt min/avg/max/mdev = 0.179/0.179/0.179/0.000 ms

- name: Ping all of the other hosts (AOSCX)
  arubanetworks.aoscx.aoscx_command:
    commands:
      - "ping {{ hostvars[item]['ansible_host'] }} repetitions 5"
  loop: "{{ groups[group_names[0]] }}"
  when:
    - hostvars[item].ansible_host != ansible_host
    - not COMMAND_STUB
  register: aoscx_ping_output

- name: Set a common variable for the ping output
  ansible.builtin.set_fact:
    ping_output: "{{ aoscx_ping_output }}"
